# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_complex_protocol_list(self):
        """Test case for get_user_complex_protocol_list

        """
        pass

    def test_get_user_complex_protocol_list_0(self):
        """Test case for get_user_complex_protocol_list_0

        """
        pass

    def test_get_user_nft_all_list(self):
        """Test case for get_user_nft_all_list

        """
        pass

    def test_get_user_nft_list(self):
        """Test case for get_user_nft_list

        """
        pass

    def test_get_user_protocol(self):
        """Test case for get_user_protocol

        """
        pass

    def test_get_user_simple_protocol_list(self):
        """Test case for get_user_simple_protocol_list

        """
        pass

    def test_get_user_simple_protocol_list_0(self):
        """Test case for get_user_simple_protocol_list_0

        """
        pass

    def test_get_user_token(self):
        """Test case for get_user_token

        """
        pass

    def test_get_user_token_all_list(self):
        """Test case for get_user_token_all_list

        """
        pass

    def test_get_user_token_authorized_list(self):
        """Test case for get_user_token_authorized_list

        """
        pass

    def test_get_user_token_list(self):
        """Test case for get_user_token_list

        """
        pass

    def test_get_user_token_list_0(self):
        """Test case for get_user_token_list_0

        """
        pass

    def test_get_user_total_balance(self):
        """Test case for get_user_total_balance

        """
        pass

    def test_get_user_total_balance_0(self):
        """Test case for get_user_total_balance_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
