# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.chain_api import ChainApi  # noqa: E501
from openapi_client.rest import ApiException


class TestChainApi(unittest.TestCase):
    """ChainApi unit test stubs"""

    def setUp(self):
        self.api = ChainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_chain_list(self):
        """Test case for get_chain_list

        """
        pass

    def test_get_chain_r(self):
        """Test case for get_chain_r

        """
        pass


if __name__ == '__main__':
    unittest.main()
