# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.protocol_api import ProtocolApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProtocolApi(unittest.TestCase):
    """ProtocolApi unit test stubs"""

    def setUp(self):
        self.api = ProtocolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_protocol_all_list_r(self):
        """Test case for get_protocol_all_list_r

        """
        pass

    def test_get_protocol_list_r(self):
        """Test case for get_protocol_list_r

        """
        pass

    def test_get_protocol_list_r_0(self):
        """Test case for get_protocol_list_r_0

        """
        pass

    def test_get_protocol_r(self):
        """Test case for get_protocol_r

        """
        pass


if __name__ == '__main__':
    unittest.main()
