# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.token_api import TokenApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self):
        self.api = TokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_token_list_by_ids_r(self):
        """Test case for get_token_list_by_ids_r

        """
        pass

    def test_get_token_r(self):
        """Test case for get_token_r

        """
        pass


if __name__ == '__main__':
    unittest.main()
