# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.wallet_api import WalletApi  # noqa: E501
from openapi_client.rest import ApiException


class TestWalletApi(unittest.TestCase):
    """WalletApi unit test stubs"""

    def setUp(self):
        self.api = WalletApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_gas_market(self):
        """Test case for get_gas_market

        """
        pass

    def test_post_balance_change(self):
        """Test case for post_balance_change

        """
        pass

    def test_post_check_tx(self):
        """Test case for post_check_tx

        """
        pass

    def test_post_estimate_gas(self):
        """Test case for post_estimate_gas

        """
        pass


if __name__ == '__main__':
    unittest.main()
