# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.account_api import AccountApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_order_list(self):
        """Test case for get_order_list

        """
        pass

    def test_get_unit_api_list(self):
        """Test case for get_unit_api_list

        """
        pass

    def test_get_unit_list(self):
        """Test case for get_unit_list

        """
        pass

    def test_get_unit_price_list(self):
        """Test case for get_unit_price_list

        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        """
        pass

    def test_get_user_logout(self):
        """Test case for get_user_logout

        """
        pass

    def test_post_coin_base_web_hook(self):
        """Test case for post_coin_base_web_hook

        """
        pass

    def test_post_order_view(self):
        """Test case for post_order_view

        """
        pass

    def test_post_user_login(self):
        """Test case for post_user_login

        """
        pass

    def test_post_user_refresh(self):
        """Test case for post_user_refresh

        """
        pass

    def test_post_user_verify(self):
        """Test case for post_user_verify

        """
        pass


if __name__ == '__main__':
    unittest.main()
