# coding: utf-8

"""
    DeBank OpenAPI

    Build for DeFi Developers.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Chain(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'community_id': 'int',
        'name': 'str',
        'logo_url': 'str',
        'native_token_id': 'str',
        'wrapped_token_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'community_id': 'community_id',
        'name': 'name',
        'logo_url': 'logo_url',
        'native_token_id': 'native_token_id',
        'wrapped_token_id': 'wrapped_token_id'
    }

    def __init__(self, id=None, community_id=None, name=None, logo_url=None, native_token_id=None, wrapped_token_id=None):  # noqa: E501
        """Chain - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._community_id = None
        self._name = None
        self._logo_url = None
        self._native_token_id = None
        self._wrapped_token_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if community_id is not None:
            self.community_id = community_id
        if name is not None:
            self.name = name
        if logo_url is not None:
            self.logo_url = logo_url
        if native_token_id is not None:
            self.native_token_id = native_token_id
        if wrapped_token_id is not None:
            self.wrapped_token_id = wrapped_token_id

    @property
    def id(self):
        """Gets the id of this Chain.  # noqa: E501

        chain id  # noqa: E501

        :return: The id of this Chain.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Chain.

        chain id  # noqa: E501

        :param id: The id of this Chain.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def community_id(self):
        """Gets the community_id of this Chain.  # noqa: E501

        Community-identified id  # noqa: E501

        :return: The community_id of this Chain.  # noqa: E501
        :rtype: int
        """
        return self._community_id

    @community_id.setter
    def community_id(self, community_id):
        """Sets the community_id of this Chain.

        Community-identified id  # noqa: E501

        :param community_id: The community_id of this Chain.  # noqa: E501
        :type: int
        """

        self._community_id = community_id

    @property
    def name(self):
        """Gets the name of this Chain.  # noqa: E501


        :return: The name of this Chain.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Chain.


        :param name: The name of this Chain.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def logo_url(self):
        """Gets the logo_url of this Chain.  # noqa: E501


        :return: The logo_url of this Chain.  # noqa: E501
        :rtype: str
        """
        return self._logo_url

    @logo_url.setter
    def logo_url(self, logo_url):
        """Sets the logo_url of this Chain.


        :param logo_url: The logo_url of this Chain.  # noqa: E501
        :type: str
        """

        self._logo_url = logo_url

    @property
    def native_token_id(self):
        """Gets the native_token_id of this Chain.  # noqa: E501

        native token  # noqa: E501

        :return: The native_token_id of this Chain.  # noqa: E501
        :rtype: str
        """
        return self._native_token_id

    @native_token_id.setter
    def native_token_id(self, native_token_id):
        """Sets the native_token_id of this Chain.

        native token  # noqa: E501

        :param native_token_id: The native_token_id of this Chain.  # noqa: E501
        :type: str
        """

        self._native_token_id = native_token_id

    @property
    def wrapped_token_id(self):
        """Gets the wrapped_token_id of this Chain.  # noqa: E501

        the erc20-wrapped of native token  # noqa: E501

        :return: The wrapped_token_id of this Chain.  # noqa: E501
        :rtype: str
        """
        return self._wrapped_token_id

    @wrapped_token_id.setter
    def wrapped_token_id(self, wrapped_token_id):
        """Sets the wrapped_token_id of this Chain.

        the erc20-wrapped of native token  # noqa: E501

        :param wrapped_token_id: The wrapped_token_id of this Chain.  # noqa: E501
        :type: str
        """

        self._wrapped_token_id = wrapped_token_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Chain, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Chain):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
